### ISSUE TITLE
Thank you very much for the EFI files

### ISSUE THREAD

**Issue by MokouTyan** [Whandcz/CoreBook_X_2022#1]
I changed those three ids. By the way, have you tested the connection of the TypeC-to-TypeC wire? Includes video output and reverse charging

我修改了那三个id，顺便问一下，你有测试过线材的连接吗？包括视频输出和反向充电

**Comment by wchanco** [comment]
你可以根据自己的情况使用hackintool生成补丁，我的显卡补丁只是适用外接HDMI，如果外接DP或者C-to-C可能要重新生成补丁

**Comment by MokouTyan** [comment]
啊，只适用于外接HDMI吗，我试了一下外接C-to-DP竟然是可以的，我去了解一下吧，非常感谢。
我看头像还以为你你是老外XD
